const songsData = [
  [
    {
      id: 1,
      name: 'Black Sabbath - War Pigs',
      species: '',
      descriptionEn: 'War Pigs was written and recorded by Black Sabbath and released in 1970. It was originally titled ‘Walpurgis’, an anniversary associated with witches and Satanists, but was changed on the recommendation of Black Sabbath’s record company. The lyrics of War Pigs take aim at military commanders, comparing them to sorcerers and “witches at black masses”. It also accuses politicians of starting wars but abdicating any responsibility for them. According to Black Sabbath vocalist Ozzy Osbourne War Pigs is a generic anti-war song; it was not specifically about Vietnam. War Pigs did not sell well as a single but has become an iconic song. Several critics consider it the best heavy metal anti-war song ever recorded.',
      descriptionRu: 'Скандальная и легендарная песня «War Pigs» со второго альбома английской хэви-метал группы Black Sabbath «Paranoid», вышедшего в 1970 году, часто, как и многие другие песни коллектива, ошибочно интерпретируется, как прославляющая дьявола. Однако даже название композиции намекает на ее антивоенное содержание. Именно этот трек Тони Айомми, Оззи Осборн, Гизер Батлер и Билл Уорд хотели сделать заглавным на своем втором альбоме, однако лейбл группы посчитал такое название слишком противоречивым и вызывающим и настоял на том, чтобы пластинка вышла под названием «Paranoid» — другого ключевого хита с диска.',
      image: './copies/playlist/classic/cover/paranoid.jpg',
      audio: './copies/playlist/classic/war_pigs.mp3',
    },
    {
      id: 2,
      name: 'Dio - Holy Diver',
      species: '',
      descriptionEn: '"Holy Diver" is a song by American heavy metal band Dio. It was released in August 1983 as the lead single from the band\'s debut album of the same name. Dio said the lyrics are about a Christ figure on another planet who sacrifices himself to redeem his people. When the people learn that he intends to leave them to save people on other planets, they selfishly ask him to stay.',
      descriptionRu: '«Holy Diver» — песня американской хеви-метал-группы Dio. Была выпущена в 1983 году как сингл с их дебютного одноимённого альбома. Дио сказал, что текст повествует о фигуре Христа на другой планете, который жертвует собой, чтобы искупить свой народ. Когда люди узнают, что он намерен покинуть их, чтобы спасти людей на других планетах, они эгоистично просят его остаться.',
      image: './copies/playlist/classic/cover/holy_diver.jpg',
      audio: './copies/playlist/classic/holy_diver.mp3',
    },
    {
      id: 3,
      name: 'Diamond Head - Am I Evil',
      species: '',
      descriptionEn: '"Am I Evil?" is a song by British heavy metal band Diamond Head. Released on the band\'s 1980 debut album Lightning to the Nations, it remains the band\'s signature song. ',
      descriptionRu: '«Am I Evil?» (с англ. — «Зло ли я?») — песня хэви-метал-группы Diamond Head, выпущенная на их дебютном альбоме Lightning to the Nations в 1980 году. Песня стала популярна сразу после выпуска в кругах любителей хэви-метала в Великобритании, а всемирную известность приобрела после кавера группы Metallica, выпущенного на обратной стороне сингла «Creeping Death» в 1984, а также на альбоме Garage Inc. The song was immediately popular amongst heavy metal fans in the United Kingdom upon its initial release,[citation needed] but only rose to international prominence after Metallica covered the song as a B-side on their 1984 single "Creeping Death"; the cover was then re-released on their 1998 cover album Garage Inc.',
      image: './copies/playlist/classic/cover/am_i_evil.jpg',
      audio: './copies/playlist/classic/am_i_evil.mp3',
    },
    {
      id: 4,
      name: 'Iron Maiden - Aces High',
      species: '',
      descriptionEn: '"Aces High" is a song by English heavy metal band Iron Maiden, written by the band\'s bassist Steve Harris. It is Iron Maiden\'s eleventh single release and the second from their fifth studio album, Powerslave. The song\'s lyrics are written from the viewpoint of a British RAF pilot fighting during the Battle of Britain (1940), the first military engagement to be fought entirely with aircraft.',
      descriptionRu: 'Aces High — одиннадцатый сингл британской хеви-метал-группы Iron Maiden. Этот сингл достиг 20 позиции в чартах синглов Британии[2], а также появился в качестве саундтрека к компьютерной игре Carmageddon II Carpocalypse Now. Текст песни посвящён британским лётчикам Второй мировой войны.',
      image: './copies/playlist/classic/cover/aces_high.jpg',
      audio: './copies/playlist/classic/aces_high.mp3',
    },
    {
      id: 5,
      name: 'Motorhead - Ace of Spades',
      species: '',
      descriptionEn: '"Ace of Spades" is a song by English heavy metal band Motörhead and the title track to the album Ace of Spades. It was released as a single in October 1980. The song opens with an overdriven bass intro played by Lemmy. For the lyrics, he said he "used gambling metaphors, mostly cards and dice—when it comes to that sort of thing, I\'m more into the one-arm bandits actually, but you can\'t really sing about spinning fruit, and the wheels coming down".',
      descriptionRu: 'Ace of Spades — песня британской рок-группы Motörhead. Первый трек одноимённого альбома. 27 октября 1980 года была издана синглом. В переводе на русский язык название песни означает «туз пик». Считается своеобразным гимном Motorhead.',
      image: './copies/playlist/classic/cover/ace_of_spades.jpg',
      audio: './copies/playlist/classic/ace_of_spades.mp3',
    },
    {
      id: 6,
      name: 'Judas Priest - Painkiller',
      species: '',
      descriptionEn: '"Painkiller" is a song by English heavy metal band Judas Priest, released in 1990. The lyrics tell the story of the Painkiller, the character featured on the cover of the album, who is a cyborg superhero who saves mankind from destruction.',
      descriptionRu: 'Painkiller — песня Judas Priest с одноименного альбома, идущая первой композицией с него и выпущенная в формате сингла в 1990 году. Многие фанаты считают эту песню лучшей в творчестве Judas Priest. Гленн Типтон заявил, что соло из этой песни является для него самым любимым. Песня была номинирована на «Грэмми» в 1991 году. ',
      image: './copies/playlist/classic/cover/painkiller.JPG',
      audio: './copies/playlist/classic/painkiller.mp3',
    },
  ],
  [
    {
      id: 1,
      name: 'Megadeth - Holy Wars... the Punishment Due',
      species: '',
      descriptionEn: '"Holy Wars... The Punishment Due" (also known as "Holy Wars") is a song by American thrash metal band Megadeth. Released in 1990. The lyrics deal with global religious conflict, particularly in Israel and Northern Ireland.',
      descriptionRu: 'Holy Wars... The Punishment Due — песня американской трэш-метал-группы Megadeth, открывающая трек-лист альбома Rust in Peace, выпущенного в 1990 году. Тексты песен посвящены глобальным религиозным конфликтам, таким как в Израиле и Северной Ирландии.',
      image: './copies/playlist/thrash/cover/rust_in_peace_megadeth.jpg',
      audio: './copies/playlist/thrash/megadeth_-_holy_wars...the_punishment_due.mp3',
    },
    {
      id: 2,
      name: 'Slayer - Angel of Death',
      species: '',
      descriptionEn: '"Angel of Death" is the opening track on American thrash metal band Slayer\'s 1986 album Reign in Blood. The lyrics and music were written by guitarist Jeff Hanneman. They detail the Nazi physician Josef Mengele\'s human experiments at the Auschwitz concentration camp during World War II. ',
      descriptionRu: '«Angel of Death» — песня американской трэш-метал-группы Slayer, открывающий трек их третьего студийного альбома Reign in Blood. Тексты и музыка были написаны гитаристом группы Джеффом Ханнеманом и основывалась на истории жизни нацистского врача Йозефа Менгеле, который проводил медицинские эксперименты над узниками концлагеря Освенцим во время Второй мировой войны.',
      image: './copies/playlist/thrash/cover/slayer_-_reign_in_blood.jpg',
      audio: './copies/playlist/thrash/slayer_-_angel_of_death.mp3',
    },
    {
      id: 3,
      name: 'Metallica - The Thing That Should Not Be',
      species: '',
      descriptionEn: '"The Thing That Should Not Be" was inspired by the Cthulhu Mythos created by famed horror writer H.P. Lovecraft, with notable direct references to The Shadow over Innsmouth and to Cthulhu himself, who is the subject matter of the song\'s chorus. It is considered the heaviest track on the album, with the main riff emulating a beast dragging itself into the sea. The Black Sabbath-influenced guitars are down-tuned, creating slow and moody ambience.',
      descriptionRu: 'Сюжет песни навеян произведениями Г. Ф. Лавкрафта о Ктулху и в частности рассказом «Тень над Иннсмутом», главный герой которого борется против потусторонних сил[31]. Она считается самой тяжёлой композицией альбома. Согласно замыслу музыкантов, её основной рифф должен передавать рёв чудовища, ползущего к морю. Звучание песни — пониженный гитарный строй, создающий тягучую и депрессивную атмосферу — отражает влияние музыки Black Sabbath',
      image: './copies/playlist/thrash/cover/master_of_puppets.jpg',
      audio: './copies/playlist/thrash/metallica_-_the_thing_that_should_not_be.mp3',
    },
    {
      id: 4,
      name: 'Exodus - The Toxic Waltz',
      species: '',
      descriptionEn: '"The Toxic Waltz" is a song by American thrash metal band Exodus, released from the band\'s third album Fabulous Disaster (1989). Although the song was never released as a single, it is one of Exodus best-known songs and has held a regular position on their concert setlist since 1989',
      descriptionRu: '«The Toxic Waltz» — песня американской трэш-метал группы Exodus, выпущенная с третьего альбома группы Fabulous Disaster (1989). Хотя песня никогда не выпускалась как сингл, она является одной из самых известных песен Exodus и регулярно занимает место в их концертном сет-листе с 1989 года.',
      image: './copies/playlist/thrash/cover/fabulous_disaster.jpeg',
      audio: './copies/playlist/thrash/exodus_-_the_toxic_waltz.mp3',
    },
    {
      id: 5,
      name: 'Testament - Disciples Of The Watch',
      species: '',
      descriptionEn: ' "Into the Pit", "The New Order", and "Disciples of the Watch" are among Testament\'s most frequently performed songs; all three of which have been played live over 600 times.',
      descriptionRu: '«Into the Pit», «The New Order» и «Disciples of the Watch» входят в число наиболее часто исполняемых песен Testament; все три из которых были сыграны вживую более 600 раз.',
      image: './copies/playlist/thrash/cover/the_new_order.jpg',
      audio: './copies/playlist/thrash/testament_-_disciples_of_the_watch.mp3',
    },
    {
      id: 6,
      name: 'S.O.D. - Freddy Krueger',
      species: '',
      descriptionEn: 'Stormtroopers of Death (abbreviated to S.O.D.) was an American crossover thrash band formed in New York City in 1985.[1] They are credited as being among the first bands to fuse hardcore punk with thrash metal into a style sometimes referred to as crossover thrash.',
      descriptionRu: 'S.O.D. (Stormtroopers of Death) — музыкальная кроссовер-трэш группа, сформированная в Нью-Йорке в 1985 году. Группа считается одним из первых кроссовер-трэш коллективов, смешавших в своём творчестве хардкор-панк и трэш-метал. ',
      image: './copies/playlist/thrash/cover/s.o.d._-_speak_english_or_die.jpg',
      audio: './copies/playlist/thrash/stormtroopers_of_death_-_freddy_krueger.mp3',
    },
  ],
  [
    {
      id: 1,
      name: 'Pantera - Revolution Is My Name',
      species: '',
      descriptionEn: '"Revolution Is My Name" reached number 28 on the Billboard\'s Mainstream Rock Tracks. The song was nominated for Best Metal Performance in the 2001 Grammys, but lost to Deftones "Elite". However, it won a 2000 Metal Edge Readers Choice Award for Song of the Year. The song\'s music video was voted as the 15th Greatest Metal Video of the 21st Century on Headbangers Ball in 2005. ',
      descriptionRu: '«Revolution Is My Name» достигла 28-го места в Billboard Mainstream Rock Tracks. Песня была номинирована на премию «Грэмми» в категории «Лучшее метал-исполнение» в 2001 году, но проиграла «Elite» Deftones. Тем не менее, в 2000 году получила награду «Выбор читателей Metal Edge» как «Песня года». Музыкальное видео на эту песню было признано 15-м величайшим метал-видео 21 века на Headbangers Ball в 2005 году.',
      image: './copies/playlist/groove/cover/reinventing_the_steel.jpg',
      audio: './copies/playlist/groove/revolution_is_my_name.mp3',
    },
    {
      id: 2,
      name: 'Sepultura - Roots Bloody Roots',
      species: '',
      descriptionEn: '"Roots Bloody Roots" is a song by Brazilian heavy metal band Sepultura, released in February 1996 as the lead single from the band\'s sixth album Roots. The song is the band\'s best known and remains a concert staple to this day, usually being performed on encores. A music video was filmed for the single which features the band performing in a catacomb as well as on the streets with a tribe of percussionists',
      descriptionRu: '«Roots Bloody Roots» — сингл с шестого альбома Roots бразильской метал-группы Sepultura, выпущенный в феврале 1996 года. Эта песня является одной из самых известных у группы и по сей день её исполняют на концертах на бис. К песне было снято два музыкальных видео, в котором группа находится в катакомбах, а также на улице с племенем перкуссионистов.',
      image: './copies/playlist/groove/cover/sepultura_roots.jpg',
      audio: './copies/playlist/groove/roots_bloody_roots.mp3',
    },
    {
      id: 3,
      name: 'Lamb Of God - Redneck',
      species: '',
      descriptionEn: '"Redneck" is the first single from the heavy metal band Lamb of God, from their fifth album Sacrament. A music video was also produced for the song.',
      descriptionRu: '«Redneck» — первый сингл хэви-метал-группы Lamb of God с их пятого альбома Sacrament. На песню также был снят видеоклип.',
      image: './copies/playlist/groove/cover/lamb_of_god_sacrament.jpg',
      audio: './copies/playlist/groove/redneck_-_lamb_of_god.mp3',
    },
    {
      id: 4,
      name: 'Machine Head - Davidian',
      species: '',
      descriptionEn: 'This song is about the Waco Siege in 1993 at Waco, Texas. Waco siege, a 51-day standoff between Branch Davidians and federal agents that ended on April 19, 1993, when the religious group’s compound near Waco, Texas, was destroyed in a fire. Nearly 80 people were killed.',
      descriptionRu: 'Песня посвящена осаде в Уэйко (Waco siege). Waco siege - осада принадлежавшего членам религиозной секты «Ветвь Давидова» ранчо в 14 км от города Уэйко в Техасе силами Федерального бюро расследований и Национальной гвардии США, длившаяся с 28 февраля по 19 апреля 1993 года. Во время событий погибло 82 члена секты, в том числе более 20 детей, а также 4 агента Бюро ATF. ',
      image: './copies/playlist/groove/cover/machine_head_burn_my_eyes.jpg',
      audio: './copies/playlist/groove/machine_head_-_davidian.mp3',
    },
    {
      id: 5,
      name: 'Ektomofr - Last Fight',
      species: '',
      descriptionEn: 'Ektomorf was founded in 1993 in Mezőkovácsháza, Hungary, a small city near the Romanian border, by Zoltán "Zoli/Zotya" Farkas. In the actual line-up Zoli/Zotya – songwriter and leader of the band – is the only remaining founder member. The band is completed by Szebasztián Simon (lead guitar), Csaba Zahorán (bass) and Dániel Szabó (drums). ',
      descriptionRu: 'Ektomorf — венгерская грув-метал группа, была основана в 1994 году, братьями Золтаном (вокал, гитара) и Чабой Фаркашами (бас-гитара). Дебютная пластинка «Hangok» (1996), сочетающая грув-метал, ню-метал и цыганскую этническую музыку, принесла группе известность на родине.',
      image: './copies/playlist/groove/cover/redemption.jpg',
      audio: './copies/playlist/groove/ektomorf_-_last_fight.mp3',
    },
    {
      id: 6,
      name: 'DevilDriver - Daybreak',
      species: '',
      descriptionEn: 'DevilDriver is an American heavy metal band from Santa Barbara, California, formed in 2002, consisting of vocalist Dez Fafara, lead guitarist Mike Spreitzer, drummer Austin D\'Amond, bassist Jon Miller and rhythm guitarist Alex Lee. The band was originally named Deathride, however, due to copyright issues and the name being taken by several bands, the band changed its name to DevilDriver.',
      descriptionRu: 'DevilDriver возникли после распада Coal Chamber, когда вокалист Дэз Фафара разошёлся в музыкальных взглядах с остальными участниками коллектива и решил создать принципиально новую по стилю и звучанию группу. ',
      image: './copies/playlist/groove/cover/trust_no_one.jpg',
      audio: './copies/playlist/groove/devildriver_-_daybreak.mp3',
    },
  ],
  [
    {
      id: 1,
      name: 'Korn - Clown',
      species: '',
      descriptionEn: '"Clown" is a song by the American nu metal band Korn. It was released as the fourth single from their self-titled debut album on July 12, 1995. ',
      descriptionRu: '«Clown» — четвёртый сингл американской ню-метал-группы Korn. Песня появилась на одноимённом первом альбоме группы. ',
      image: './copies/playlist/nu/cover/korn-korn.jpg',
      audio: './copies/playlist/nu/04_-_clown.mp3',
    },
    {
      id: 2,
      name: 'Coal Chamber - Not Living',
      species: '',
      descriptionEn: 'Coal Chamber was an American nu metal band formed by Dez Fafara and Meegs Rascón in Los Angeles, California in 1993.',
      descriptionRu: 'Coal Chamber — ню-метал-группа из Лос-Анджелеса, образованная в 1993 году вокалистом Брэдли «Дэзом» Фафарой и гитаристом Мигелем «Мигсом» Расконом. Одна из первых «мрачных» ню-метал-групп, выделявшаяся своим стилем, более близким субкультуре готов, чем хип-хопу.',
      image: './copies/playlist/nu/cover/coal_chamber_–_giving_the_devil_his_due.jpg',
      audio: './copies/playlist/nu/coal_chamber_-_not_living_(original_version).mp3',
    },
    {
      id: 3,
      name: 'Deftones - My Own Summer (Show it)',
      species: '',
      descriptionEn: '"My Own Summer (Shove It)" is a song by American alternative metal band Deftones, released in 1997 by Maverick Records as the first single from their second album Around the Fur. It was Deftones\' first charting single, reaching number 29 in the UK Singles Chart.',
      descriptionRu: '«My Own Summer (Shove It)» — песня американской альтернативной метал группы Deftones, выпущенная как сингл с альбома Around the Fur 22 декабря 1997 года на звукозаписывающем лейбле Maverick Records. Это был первый сингл, который достиг 29 позиции в английском чарте UK Singles Chart',
      image: './copies/playlist/nu/cover/deftones_-_around_the_fur.jpg',
      audio: './copies/playlist/nu/deftones_-_my_own_summer_(shove_it).mp3',
    },
    {
      id: 4,
      name: 'Godsmack - I Stand Alone',
      species: '',
      descriptionEn: '"I Stand Alone" is a song by the American rock band Godsmack. It served as a single from the Scorpion King soundtrack on March 5, 2002. It would reappear on Godsmack\'s third studio album, Faceless, the following year. It won a 2002 Metal Edge Readers Choice Award for "Song of the Year From a Movie Soundtrack.',
      descriptionRu: '«I Stand Alone» — песня американской рок-группы Godsmack, выпущенная как первый сингл с третьего студийного альбома Faceless. Песня также является единственным синглом с альбома The Scorpion King и основным саундтреком к фильму Царь скорпионов. В 2002 году он получил награду «Song of the Year From a Movie Soundtrack» по версии журнала Metal Edge',
      image: './copies/playlist/nu/cover/godsmack_faceless.jpg',
      audio: './copies/playlist/nu/godsmack_-_i_stand_alone.mp3',
    },
    {
      id: 5,
      name: 'Disturbed - Stricken',
      species: '',
      descriptionEn: '"Stricken" is a song by the American heavy metal band Disturbed. The song was released on July 25, 2005, as the second single from their third studio album Ten Thousand Fists. "Stricken" was certified gold in the United States by the Recording Industry Association of America on August 18, 2008, for selling 500,000 copies. It is one of the first of Disturbed\'s songs to include a guitar solo.',
      descriptionRu: '«Stricken» — сингл американской рок-группы Disturbed. Он был выпущен 25 июля 2005 года. Это второй по счёту сингл с третьего альбома коллектива — Ten Thousand Fists. «Stricken» удостоился золотого статуса в США 18 августа 2008 года, продав 500 000 копий. Это одна из первых композиций группы, где появилось гитарное соло',
      image: './copies/playlist/nu/cover/disturbed_ten_thousand_fists.jpg',
      audio: './copies/playlist/nu/disturbed_-_stricken.mp3',
    },
    {
      id: 6,
      name: 'Ill Niño - I Am Loco',
      species: '',
      descriptionEn: 'Ill Niño is an American metal band formed in Union City, New Jersey, in 1998 by drummer and percussionist Dave Chavarri. They have released seven studio albums, two EPs and one compilation album, totaling in over 1.3 million worldwide album sales',
      descriptionRu: 'Ill Niño — американская ню-метал-группа латиноамериканского происхождения, основанная в 1998 году в Нью-Джерси. Коллектив исполняет ню-метал с примесью латиноамериканского фольклора, начиная с третьего студийного альбома в песнях группы появились элементы металкора. Группа выпустила семь студийных альбомов с общим числом продаж более миллиона копий. ',
      image: './copies/playlist/nu/cover/ill_niño_revolution_revolucion.jpg',
      audio: './copies/playlist/nu/ill_niño_-_i_am_loco.mp3',
    },
  ],
  [
    {
      id: 1,
      name: 'Electric Wizard - Return Trip',
      species: '',
      descriptionEn: 'Electric Wizard are an English doom metal band from Dorset. The band formed in 1993 and have recorded nine studio albums, two of which have been considered genre landmarks: Come My Fanatics… (1997) and Dopethrone (2000). Electric Wizard\'s brand of doom metal incorporates stoner and sludge traits, with lyrics focusing on the occult, witchcraft, H. P. Lovecraft, horror films and cannabis. In 2014 they formed Witchfinder Records, an imprint of Spinefarm Records, on which they plan to release all future albums. ',
      descriptionRu: 'Electric Wizard — британская дум метал-группа, образованная в 1993 году в Дорсете, Англия, вокалистом и автором песен Джастином Оборном, и исполняющая дум-метал с элементами стоунер- и сладж-метала и текстами в основном оккультной тематики. Такие альбомы как Come My Fanatics... и Dopethrone считаются классическими в своём жанре, а Electric Wizard выделяется как одна из основополагающих групп на дум/стоунер-метал-сцене.',
      image: './copies/playlist/stoner/cover/come_my_fanatics_electric_wizard.jpg',
      audio: './copies/playlist/stoner/electric_wizard_-_return_trip.mp3',
    },
    {
      id: 2,
      name: 'Acid King - Electric Machine',
      species: '',
      descriptionEn: 'Acid King is an American stoner metal band from San Francisco, California. The band\'s name was inspired by the crimes of Ricky Kasso, who murdered his friend Gary Lauwers in Northport, New York on June 19, 1984. Kasso was nicknamed "Acid King" by his peers due to his chronic hallucinogenic drug use. The band\'s self-titled debut EP features a photograph of Kasso on its cover.',
      descriptionRu: 'Acid King — американская группа из Сан-Франциско (Калифорния), играющая музыку в жанре стоунер-рок и дум-метал. Название группы было вдохновлено преступлениями Рики Кассо, который убил своего друга Гэри Лоуэрса в Нортпорте, штат Нью-Йорк, 19 июня 1984 года. Коллеги прозвали Кассо «кислотным королем» из-за его хронического употребления галлюциногенных наркотиков. На обложке одноименного дебютного EP группы изображена фотография Кассо.',
      image: './copies/playlist/stoner/cover/acid_king_busse_woods.jpg',
      audio: './copies/playlist/stoner/electric_machine.mp3',
    },
    {
      id: 3,
      name: 'Bongzilla - Stone a Pig',
      species: '',
      descriptionEn: 'Bongzilla is an American stoner metal band that formed in Madison, Wisconsin in 1995. Much of Bongzilla\'s lyrics are centered around cannabis use and similar themes.',
      descriptionRu: 'Bongzilla - американская стонер-метал группа, которая образовалась в Мэдисоне, штат Висконсин, в 1995 году. Большая часть текстов Бонгиллы сосредоточена вокруг употребления каннабиса и подобных тем.',
      image: './copies/playlist/stoner/cover/bongzilla_gateway.jpg',
      audio: './copies/playlist/stoner/bongzilla_-_stone_a_pig.mp3',
    },
    {
      id: 4,
      name: 'YOB - Burning the Altar',
      species: '',
      descriptionEn: 'YOB is an American doom metal band from Eugene, Oregon, composed of singer/guitarist Mike Scheidt, bassist Aaron Rieseberg, and drummer Travis Foster. Their most recent studio album Our Raw Heart was released in June 2018. ',
      descriptionRu: 'YOB — американская дум-метал группа из Юджина (Орегон). В состав группы входят Майк Шайдт (гитара, вокал), Аарон Ризберг (бас-гитара) и Трэвис Фостер (барабаны). Последняя студийная работа группы, полноформатный альбом Our Raw Heart, вышел в июне 2018 года. ',
      image: './copies/playlist/stoner/cover/the_great_cessation_.jpg',
      audio: './copies/playlist/stoner/yob_-_the_great_cessation_(reissue)_-_01_burning_the_altar.mp3',
    },
    {
      id: 5,
      name: 'Crowbar - Lasting Dose',
      species: '',
      descriptionEn: 'Crowbar is an American sludge metal band formed in New Orleans, Louisiana, in 1990. The band is fronted by vocalist/guitarist Kirk Windstein, Crowbar\'s sole constant member. Through infusing a slow, low-keyed, brooding doom metal sound with the aggression of hardcore punk, they pioneered a style known as sludge metal',
      descriptionRu: 'Crowbar — это не столько группа, сколько сольный проект гитариста и вокалиста Кирка Уиндстейна (сейчас он единственный оригинальный участник группы), лысого бородача, который всем своим видом показывает, чего стоит ждать от его музыки. Его совершенно заслуженно называют крёстным отцом нью-орлеанского сладжа, да и сладжа вообще.',
      image: './copies/playlist/stoner/cover/crowbar_sonic_excess.jpg',
      audio: './copies/playlist/stoner/crowbar_-_the_lasting_dose.mp3',
    },
    {
      id: 6,
      name: 'Sleep - Dragonaut',
      species: '',
      descriptionEn: ' Sleep is an American doom metal power trio from San Jose, California. The band earned critical and record label attention early in its career. Critic Eduardo Rivadavia describes them as "perhaps the ultimate stoner rock band" and notes they exerted a strong influence on heavy metal in the 1990s. However, conflict with its record company contributed to Sleep\'s breakup by the end of the decade. The band reformed in 2009 and has played sporadic live dates internationally since. In 2018, Sleep released their fourth and comeback album, The Sciences, to critical acclaim.',
      descriptionRu: '',
      image: './copies/playlist/stoner/cover/holy_mountain.jpg',
      audio: './copies/playlist/stoner/sleep_-_dragonaut.mp3',
    },
  ],
  [
    {
      id: 1,
      name: 'Meshuggah - Bleed',
      species: '',
      descriptionEn: 'Meshuggah, whose name is taken from the Hebrew and Yiddish word for “crazy”, is a five-piece band from Umeå, Sweden, founded in 1987. The band\'s style is most easily described as djent or groove metal with some jazz influence. ',
      descriptionRu: 'Meshuggah - шведская метал-группа, соединяющая грув-метал и прогрессив-метал. Образована в 1987 году в городе Умео. Название группы являет собой транслитерацию с иврита на английский язык слова משוגע ("сумасшедший"; на иврите произносится как "мешуга" с ударением на последний слог). Стиль группы легче всего описать как джент или грув-метал с некоторым влиянием джаза.',
      image: './copies/playlist/progressive/cover/meshuggah_obzen.jpg',
      audio: './copies/playlist/progressive/bleed.mp3',
    },
    {
      id: 2,
      name: 'Animals As Leaders - CAFO',
      species: '',
      descriptionEn: 'Animals as Leaders is a Washington, D.C. based instrumental/progressive-metal project formed by guitarist Tosin Abasi in 2007. Their self-titled debut album was released in April 2009 by Prosthetic Records. The name Animals as Leaders was inspired by Daniel Quinn\'s 1992 novel Ishmael, which addresses anthropocentrism.',
      descriptionRu: 'Animals as Leaders — американский музыкальный коллектив, исполняющий музыку в стиле прогрессивный метал. Группа была создана в поддержку своего соло-проекта Тосином Абаси (Tosin Abasi), игравшим ранее в группе Reflux. Название группы было вдохновлено новеллой «Измаил» Дэниэла Куинна, касающейся вопросов антропоцентризма. ',
      image: './copies/playlist/progressive/cover/animals_as_leaders.jpg',
      audio: './copies/playlist/progressive/animals_as_leaders_-_cafo.mp3',
    },
    {
      id: 3,
      name: 'After the Burial - Exit, Exist',
      species: '',
      descriptionEn: 'After the Burial is an American metal band from White Bear Lake, Minnesota, United States formed in 2004. With the release of their album "Rareform", which showcases their talented use of 7 and 8-string guitars, they have solidified themselves as pioneers of the instrument.',
      descriptionRu: 'After the Burial — американская прогрессив-метал-группа из города Миннеаполис, штат Миннесота, сформированная в 2004 году. Группа считается одним из ключевых участников развития таких поджанров как прогрессивный металкор и джент.',
      image: './copies/playlist/progressive/cover/evergreen_cover.jpg',
      audio: './copies/playlist/progressive/after_the_burial_-_exit,_exist.mp3',
    },
    {
      id: 4,
      name: 'Monuments - I, The Destroyer',
      species: '',
      descriptionEn: 'Monuments are a British progressive metal band formed by former Fellsilent guitarist, John Browne, and former Tony Danza Tapdance Extravaganza guitarist, Josh Travis.',
      descriptionRu: 'Monuments — британская прогрессив-метал-группа, созданная бывшим гитаристом Fellsilent - Джоном Брауном и бывшим гитаристом Tony Danza Tapdance Extravaganza - Джошем Трэвисом.',
      image: './copies/playlist/progressive/cover/monuments_the_amanuensis_album_artwork.jpeg',
      audio: './copies/playlist/progressive/monuments_-_i,_the_destroyer.mp3',
    },
    {
      id: 5,
      name: 'Volumes - Wormholes',
      species: '',
      descriptionEn: 'Volumes is an American djent band from Los Angeles, California formed in 2009.',
      descriptionRu: 'Volumes — американская прогрессив-металкор-группа из Лос-Анджелеса',
      image: './copies/playlist/progressive/cover/volumes-via.jpg',
      audio: './copies/playlist/progressive/volumes_-_wormholes.mp3',
    },
    {
      id: 6,
      name: 'Mick Gordon - Bfg Division',
      species: '',
      descriptionEn: 'Mick Gordon is an Australian composer and sound designer whose compositions aim to transcend the perceptual boundary between music and its context.',
      descriptionRu: 'Мик Го́рдон — австралийский композитор и саунд-дизайнер, пишущий музыку преимущественно для компьютерных игр. ',
      image: './copies/playlist/progressive/cover/doom_ost.jpg',
      audio: './copies/playlist/progressive/mick_gordon_-_bfg_division.mp3',
    },
  ],
  [
    {
      id: 1,
      name: 'Cannibal Corpse - Frantic Disembowelment',
      species: '',
      descriptionEn: 'Cannibal Corpse is an American death metal band formed in Buffalo, New York in 1988. Bassist Alex Webster came up with the name Cannibal Corpse. They have had several lineup changes since their inception, with Webster and drummer Paul Mazurkiewicz as the only constant members. The members of Cannibal Corpse were originally inspired by thrash metal bands like Metallica, Slayer, Dark Angel, Sadus, Sodom and Kreator and other death metal bands such as Possessed, Autopsy, Morbid Angel and Death. The band\'s album art (most often by Vincent Locke) and lyrics, drawing heavily on horror fiction and horror films, are highly controversial. At different times, several countries, such as Germany and Russia, have banned Cannibal Corpse from performing within their borders, or have banned the sale and display of original Cannibal Corpse album covers.',
      descriptionRu: 'Cannibal Corpse — американская дэт-метал-группа, основанная в 1988 году в Буффало, штат Нью-Йорк. Cвоим скандальным дебютом «Eaten back to life» музыканты заявили себя пионерами на абсолютно новых, неизведанных границах экстремальной музыки.',
      image: './copies/playlist/death/cover/the_wretched_spawn.jpg',
      audio: './copies/playlist/death/cannibal_corpse_-_frantic_disembowelment.mp3',
    },
    {
      id: 2,
      name: 'Bloodbath - Eaten',
      species: '',
      descriptionEn: 'Bloodbath is a Swedish death metal supergroup from Stockholm, formed in 1998. The song Eaten is inspired by a true story which took place in Germany. In 2001, Armin Meiwes killed and ate a voluntary victim he met over the internet, named Bernd Jürgen Armando Brandes.',
      descriptionRu: 'Bloodbath — шведская дэт-метал-супергруппа, объединила в себе множество известных и авторитетных музыкантов шведской метал-сцены. Песня Eaten, вдохновлена ​​реальной историей, которая произошла в Германии. В 2001 году Армин Мейвес убил и съел берлинского программиста Юргена Брандеса с его добровольного согласия.',
      image: './copies/playlist/death/cover/eaten.jpg',
      audio: './copies/playlist/death/bloodbath_-_eaten.mp3',
    },
    {
      id: 3,
      name: 'Necrophagist - Advanced Corpse Tumor',
      species: '',
      descriptionEn: 'Necrophagist was founded in early 1992 in Karlsruhe, Germany to integrate the fury of grinding, fast death metal with technical music. ',
      descriptionRu: 'Necrophagist — музыкальный коллектив, играющий в стиле техничный дэт-метал с элементами прогрессива. Был образован в 1992 году в Германии. ',
      image: './copies/playlist/death/cover/onset_of_putrefaction.jpg',
      audio: './copies/playlist/death/necrophagist_-_advanced_corpse_tumor.mp3',
    },
    {
      id: 4,
      name: 'Death - the Philosopher',
      species: '',
      descriptionEn: 'Death was an American death metal band formed in Altamonte Springs, Florida in 1984 by guitarist and vocalist Chuck Schuldiner. Death is considered to be among the most influential bands in heavy metal and a pioneering force in the extreme metal subgenre of death metal. The band\'s debut album, Scream Bloody Gore, has been widely regarded as one of the first death metal records, alongside the first records from Possessed and Necrophagia. ',
      descriptionRu: 'Death — американская метал-группа, основанная в 1983 году в США и распавшаяся в 2001 году из-за смерти её основателя Чака Шульдинера 13 декабря 2001 года. Оказала наибольшее влияние на развитие жанра дэт-метал. Вокалист, гитарист и автор текстов Чак Шульдинер считается одним из первопроходцев жанра, а альбом группы под названием «Scream Bloody Gore» считается эталоном дэт-метала',
      image: './copies/playlist/death/cover/individual_thought_patterns.jpg',
      audio: './copies/playlist/death/death_-_the_philosopher.mp3',
    },
    {
      id: 5,
      name: 'Carcass - Heartwork',
      species: '',
      descriptionEn: 'Carcass is an English death metal band from Liverpool, which was formed in 1985.',
      descriptionRu: 'Carcass — английская дэт-метал-группа из Ливерпуля, образованная в 1985 году',
      image: './copies/playlist/death/cover/carcass_heartwork.jpg',
      audio: './copies/playlist/death/carcass_-_heartwork.mp3',
    },
    {
      id: 6,
      name: 'Nile - Kafir',
      species: '',
      descriptionEn: 'Nile is an American death metal band from Greenville, South Carolina, United States, formed in 1993. Their music and lyrics are inspired by Ancient Egyptian and Near Eastern mysticism, history, religion, and ancient art, as well as the works of H.P. Lovecraft.',
      descriptionRu: 'Nile - американская группа, играющая в стиле техничный дэт-метал. Характерной чертой музыки Nile — является смешивание традиционных египетских мотивов с современным дэт-металом. Группа в своём творчестве использует симфонические элементы в написании песен, они смогли создать невероятное сочетание техничного дэт-метала с традиционной восточной музыкой. Написанием лирики занимается один из основателей группы Карл Сандерс. В лирике песен он отдаёт предпочтение древнеегипетским мифам, легендам, которые изначально были вырезаны в виде иероглифов на древних зданиях, на папирусных свитках.',
      image: './copies/playlist/death/cover/nile_those_whom_the_gods_detest.jpg',
      audio: './copies/playlist/death/nile_-_kafir!.mp3',
    },
  ],
];

export default songsData;
