const songsData = [
  [
    {
      id: 1,
      name: 'Black Sabbath - War Pigs',
      species: '',
      description: '',
      image: './copies/playlist/classic/cover/paranoid.jpg',
      audio: './copies/playlist/classic/war_pigs.mp3',
    },
    {
      id: 2,
      name: 'Dio - Holy Diver',
      species: '',
      description: '',
      image: './copies/playlist/classic/cover/holy_diver.jpg',
      audio: './copies/playlist/classic/holy_diver.mp3',
    },
    {
      id: 3,
      name: 'Diamond Head - Am I Evil',
      species: '',
      description: '',
      image: './copies/playlist/classic/cover/am_i_evil.jpg',
      audio: './copies/playlist/classic/am_i_evil.mp3',
    },
    {
      id: 4,
      name: 'Iron Maiden - Aces High',
      species: '',
      description: '',
      image: './copies/playlist/classic/cover/aces_high.jpg',
      audio: './copies/playlist/classic/aces_high.mp3',
    },
    {
      id: 5,
      name: 'Motorhead - Ace of Spades',
      species: '',
      description: '',
      image: './copies/playlist/classic/cover/ace_of_spades.jpg',
      audio: './copies/playlist/classic/ace_of_spades.mp3',
    },
    {
      id: 6,
      name: 'Judas Priest - Painkiller',
      species: '',
      description: '',
      image: './copies/playlist/classic/cover/painkiller.JPG',
      audio: './copies/playlist/classic/painkiller.mp3',
    },    
  ],
  [
    {
      id: 1,
      name: 'Megadeth - Holy Wars... the Punishment Due',
      species: '',
      description: '',
      image: './copies/playlist/thrash/cover/rust_in_peace_megadeth.jpg',
      audio: './copies/playlist/thrash/megadeth_-_holy_wars...the_punishment_due.mp3',
    },
    {
      id: 2,
      name: 'Slayer - Angel of Death',
      species: '',
      description: '',
      image: './copies/playlist/thrash/cover/slayer_-_reign_in_blood.jpg',
      audio: './copies/playlist/thrash/slayer_-_angel_of_death.mp3',
    },
    {
      id: 3,
      name: 'Metallica - Battery',
      species: '',
      description: '',
      image: './copies/playlist/thrash/cover/master_of_puppets.jpg',
      audio: './copies/playlist/thrash/metallica_-_battery_.mp3',
    },
    {
      id: 4,
      name: 'Exodus - The Toxic Waltz',
      species: '',
      description: '',
      image: './copies/playlist/thrash/cover/fabulous_disaster.jpeg',
      audio: './copies/playlist/thrash/exodus_-_the_toxic_waltz.mp3',
    },
    {
      id: 5,
      name: 'Testament - Disciples Of The Watch',
      species: '',
      description: '',
      image: './copies/playlist/thrash/cover/the_new_order.jpg',
      audio: './copies/playlist/thrash/testament_-_disciples_of_the_watch.mp3',
    },
    {
      id: 6,
      name: 'S.O.D. - Freddy Kreuger',
      species: '',
      description: '',
      image: './copies/playlist/thrash/cover/s.o.d._-_speak_english_or_die.jpg',
      audio: './copies/playlist/thrash/stormtroopers_of_death_-_freddy_krueger.mp3',
    },    
  ],
  [
    {
      id: 1,
      name: 'Pantera - Revolution Is My Name',
      species: '',
      description: '',
      image: './copies/playlist/groove/cover/reinventing_the_steel.jpg',
      audio: './copies/playlist/groove/revolution_is_my_name.mp3',
    },
    {
      id: 2,
      name: 'Sepultura - Roots Bloody Roots',
      species: '',
      description: '',
      image: './copies/playlist/groove/cover/sepultura_roots.jpg',
      audio: './copies/playlist/groove/roots_bloody_roots.mp3',
    },
    {
      id: 3,
      name: 'Lamb Of God - Redneck',
      species: '',
      description: '',
      image: './copies/playlist/groove/cover/lamb_of_god_sacrament.jpg',
      audio: './copies/playlist/groove/redneck_-_lamb_of_god.mp3',
    },
    {
      id: 4,
      name: 'Machine Head - Davidian',
      species: '',
      description: '',
      image: './copies/playlist/groove/cover/machine_head_burn_my_eyes.jpg',
      audio: './copies/playlist/groove/machine_head_-_davidian.mp3',
    },
    {
      id: 5,
      name: 'Ektomofr - Last Fight',
      species: '',
      description: '',
      image: './copies/playlist/groove/cover/redemption.jpg',
      audio: './copies/playlist/groove/ektomorf_-_last_fight.mp3',
    },
    {
      id: 6,
      name: 'DevilDriver - Daybreak',
      species: '',
      description: '',
      image: './copies/playlist/groove/cover/trust_no_one.jpg',
      audio: './copies/playlist/groove/devildriver_-_daybreak.mp3',
    },    
  ],
  [
    {
      id: 1,
      name: 'Korn - Clown',
      species: '',
      description: '',
      image: './copies/playlist/nu/cover/korn-korn.jpg',
      audio: './copies/playlist/nu/04_-_clown.mp3',
    },
    {
      id: 2,
      name: 'Coal Chamber - Not Living',
      species: '',
      description: '',
      image: './copies/playlist/nu/cover/coal_chamber_–_giving_the_devil_his_due.jpg',
      audio: './copies/playlist/nu/coal_chamber_-_not_living_(original_version).mp3',
    },
    {
      id: 3,
      name: 'Deftones - My Own Summer (Show it)',
      species: '',
      description: '',
      image: './copies/playlist/nu/cover/deftones_-_around_the_fur.jpg',
      audio: './copies/playlist/nu/deftones_-_my_own_summer_(shove_it).mp3',
    },
    {
      id: 4,
      name: 'Godsmack - I Stand Alone',
      species: '',
      description: '',
      image: './copies/playlist/nu/cover/godsmack_faceless.jpg',
      audio: './copies/playlist/nu/godsmack_-_i_stand_alone.mp3',
    },
    {
      id: 5,
      name: 'Distuber - Stricken',
      species: '',
      description: '',
      image: './copies/playlist/nu/cover/disturbed_ten_thousand_fists.jpg',
      audio: './copies/playlist/nu/disturbed_-_stricken.mp3',
    },
    {
      id: 6,
      name: 'Ill Niño - I Am Loco',
      species: '',
      description: '',
      image: './copies/playlist/nu/cover/ill_niño_revolution_revolucion.jpg',
      audio: './copies/playlist/nu/ill_niño_-_i_am_loco.mp3',
    },    
  ],
  [
    {
      id: 1,
      name: 'Electric Wizard - Return Trip',
      species: '',
      description: '',
      image: './copies/playlist/stoner/cover/come_my_fanatics_electric_wizard.jpg',
      audio: './copies/playlist/stoner/electric_wizard_-_return_trip.mp3',
    },
    {
      id: 2,
      name: 'Acid King - Electric Machine',
      species: '',
      description: '',
      image: './copies/playlist/stoner/cover/acid_king_busse_woods.jpg',
      audio: './copies/playlist/stoner/electric_machine.mp3',
    },
    {
      id: 3,
      name: 'Bongzilla - Stone a Pig',
      species: '',
      description: '',
      image: './copies/playlist/stoner/cover/bongzilla_gateway.jpg',
      audio: './copies/playlist/stoner/bongzilla_-_stone_a_pig.mp3',
    },
    {
      id: 4,
      name: 'YOB - Burning the Altar',
      species: '',
      description: '',
      image: './copies/playlist/stoner/cover/the_great_cessation_.jpg',
      audio: './copies/playlist/stoner/yob_-_the_great_cessation_(reissue)_-_01_burning_the_altar.mp3',
    },
    {
      id: 5,
      name: 'Crowbar - Lasting Dose',
      species: '',
      description: '',
      image: './copies/playlist/stoner/cover/crowbar_sonic_excess.jpg',
      audio: './copies/playlist/stoner/crowbar_-_the_lasting_dose.mp3',
    },
    {
      id: 6,
      name: 'TruckFighters - Desert Cruiser',
      species: '',
      description: '',
      image: './copies/playlist/stoner/cover/gravity_x_album.jpg',
      audio: './copies/playlist/stoner/truckfighters_-_desert_cruiser.mp3',
    },    
  ],
  [
    {
      id: 1,
      name: 'Meshuggah - Bleed',
      species: '',
      description: '',
      image: './copies/playlist/progressive/cover/meshuggah_obzen.jpg',
      audio: './copies/playlist/progressive/bleed.mp3',
    },
    {
      id: 2,
      name: 'Animals As Leaders - CAFO',
      species: '',
      description: '',
      image: './copies/playlist/progressive/cover/animals_as_leaders.jpg',
      audio: './copies/playlist/progressive/animals_as_leaders_-_cafo.mp3',
    },
    {
      id: 3,
      name: 'Jinjer - I Speak Astronomy',
      species: '',
      description: '',
      image: './copies/playlist/progressive/cover/jinjer_—_king_of_everything.jpg',
      audio: './copies/playlist/progressive/jinjer_-_i_speak_astronomy.mp3',
    },
    {
      id: 4,
      name: 'Monuments - Doxa',
      species: '',
      description: '',
      image: './copies/playlist/progressive/cover/monuments_-_gnosis.jpg',
      audio: './copies/playlist/progressive/monuments_-_doxa.mp3',
    },
    {
      id: 5,
      name: 'Volumes - Wormholes',
      species: '',
      description: '',
      image: './copies/playlist/progressive/cover/volumes-via.jpg',
      audio: './copies/playlist/progressive/volumes_-_wormholes.mp3',
    },
    {
      id: 6,
      name: 'Mick Gordon - Bfg Division',
      species: '',
      description: '',
      image: './copies/playlist/progressive/cover/doom_ost.jpg',
      audio: './copies/playlist/progressive/mick_gordon_-_bfg_division.mp3',
    },    
  ],
  [
    {
      id: 1,
      name: 'Cannibal Corpse - Frantic Disembowelment',
      species: '',
      description: '',
      image: './copies/playlist/death/cover/the_wretched_spawn.jpg',
      audio: './copies/playlist/death/cannibal_corpse_-_frantic_disembowelment.mp3',
    },
    {
      id: 2,
      name: 'Bloodbath - Eaten',
      species: '',
      description: '',
      image: './copies/playlist/death/cover/eaten.jpg',
      audio: './copies/playlist/death/bloodbath_-_eaten.mp3',
    },
    {
      id: 3,
      name: 'Necrophagist - Advanced Corpse Tumor',
      species: '',
      description: '',
      image: './copies/playlist/death/cover/onset_of_putrefaction.jpg',
      audio: './copies/playlist/death/necrophagist_-_advanced_corpse_tumor.mp3',
    },
    {
      id: 4,
      name: 'Death - the Philosopher',
      species: '',
      description: '',
      image: './copies/playlist/death/cover/individual_thought_patterns.jpg',
      audio: './copies/playlist/death/death_-_the_philosopher.mp3',
    },
    {
      id: 5,
      name: 'Carcass - Heartwork',
      species: '',
      description: '',
      image: './copies/playlist/death/cover/carcass_heartwork.jpg',
      audio: './copies/playlist/death/carcass_-_heartwork.mp3',
    },
    {
      id: 6,
      name: 'Nile - Kafir',
      species: '',
      description: '',
      image: './copies/playlist/death/cover/nile_those_whom_the_gods_detest.jpg',
      audio: './copies/playlist/death/nile_-_kafir!.mp3',
    },    
  ],
]

export default songsData;